file_min_updated_hours: 12
sources:
  ripienaar/free-for-dev:
  public-apis/public-apis:
    files:
      README.md:
        index: true
        options:
          type: table
          max_heading_level: 3
  sindresorhus/awesome:
    files:
      readme.md:
        index: true
  EbookFoundation/free-programming-books:
    files:
      books/free-programming-books-langs.md:
        index: true
      books/free-programming-books-zh.md:
      books/free-programming-books-subjects.md:
        options:
          max_heading_level: 3
  vinta/awesome-python:
  awesome-selfhosted/awesome-selfhosted:
  avelino/awesome-go:
  vuejs/awesome-vue:
    files:
      README.md:
        index: true
        options:
          min_heading_level: 3
  rust-unofficial/awesome-rust:
    files:
      README.md:
        index: true
        options:
          min_heading_level: 3
  josephmisiti/awesome-machine-learning:
  jaywcjlove/awesome-mac:
  MunGell/awesome-for-beginners:
  paragonie/awesome-appsec:
    files:
      README.md:
        index: true
        options:
          min_heading_level: 2
          type: heading
          heading_level: 3
          max_heading_level: 2
  stevemao/awesome-git-addons:
    files:
      README.md:
        index: true
        options:
          min_heading_level: 2
          type: heading
          heading_level: 3
          max_heading_level: 2
  agarrharr/awesome-macos-screensavers:
    files:
      readme.md:
        index: true
        options:
          min_heading_level: 2
          type: heading
          heading_level: 3
          max_heading_level: 2
  Solido/awesome-flutter:
    files:
      source.md:
        index: true
  nayafia/awesome-maintainers:
    files:
      README.md:
        index: true
        options:
          max_heading_level: 1
          is_parse_category: false
  KotlinBy/awesome-kotlin:
    default_branch: readme
    files:
      README.md:
        index: true
        options:
          max_heading_level: 2
  alexk111/awesome-bitcoin-payment-processors:
    files:
      README.md:
        index: true
        options:
          max_heading_level: 2
          type: table
  hackerkid/Mind-Expanding-Books:
    files:
      README.md:
        index: true
        options:
          type: table
  j0hnm4r5/awesome-creative-technology:
    files:
      readme.md:
        index: true
        options:
          type: table
  therebelrobot/awesome-workshopper:
    files:
      README.md:
        index: true
        options:
          type: table
  victorlaerte/awesome-it-quotes:
    files:
      README.md:
        index: true
        options:
          type: table
  wasabeef/awesome-android-ui:
    files:
      README.md:
        index: true
        options:
          type: table
          min_heading_level: 1
          max_heading_level: 1
  lnishan/awesome-competitive-programming:
    files:
      README.md:
        index: true
        options:
          type: table
  ramitsurana/awesome-kubernetes:
    files:
      docs/README.md:
        index: true
  gaerae/awesome-algorithms-education:
    files:
      readme-en.md:
        index: true
